from enum import Enum


class ErrorCode(str, Enum):
    # Generic
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    THROTTLED = "THROTTLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Auth domain
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_EMAIL_TAKEN = "AUTH_EMAIL_TAKEN"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"

    # Baby / profile
    BABY_NOT_FOUND = "BABY_NOT_FOUND"
    BABY_PROFILE_REQUIRED = "BABY_PROFILE_REQUIRED"
    BABY_INVALID_GA = "BABY_INVALID_GA"

    # Chat / RAG
    CHAT_CONVERSATION_NOT_FOUND = "CHAT_CONVERSATION_NOT_FOUND"
    RAG_RETRIEVAL_FAILED = "RAG_RETRIEVAL_FAILED"
    RAG_EMBEDDING_FAILED = "RAG_EMBEDDING_FAILED"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
