# Generated by Django 5.1.3 on 2026-05-14 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('gestational_age_weeks', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', '-created_at'], name='babies_baby_parent__cdcb89_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gestational_age_weeks__gte', 22), ('gestational_age_weeks__lte', 41)), name='baby_ga_weeks_range')],
            },
        ),
    ]
