# Generated by Django 5.1.3 on 2026-05-14 20:56

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('topic', models.SlugField(max_length=64)),
                ('locale', models.CharField(db_index=True, default='en', max_length=8)),
                ('evidence_level', models.CharField(choices=[('guideline', 'Clinical guideline'), ('systematic_review', 'Systematic review'), ('rct', 'Randomised controlled trial'), ('observational', 'Observational'), ('expert', 'Expert opinion'), ('patient_ed', 'Patient education')], default='patient_ed', max_length=32)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'locale'], name='rag_vectord_topic_9978cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.vectordocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rag_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
